package tampilan;

import common.JasaType;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import koneksi.DatabaseConnection;
import java.sql.*;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author winda
 */
public class FormBengkel extends javax.swing.JFrame {
    private Connection conn= new DatabaseConnection().connect();
    private DefaultTableModel tabmode;

    private static Object infocbJamBuka;

    /**
     * Creates new form NewJFrame
     */
    public FormBengkel() {
        initComponents();
        datatable();
        kosong();
        aktif();
    }
    
    void aktif() {
        bengkelid.setEnabled(true);
        namabengkel.setEnabled(true);
        kodebengkel.setEnabled(true);
        alamat.setEnabled(true);
        notelp.setEnabled(true);
        bengkelid.requestFocus();
    }
    
    void kosong(){
        bengkelid.setText("");
        namabengkel.setText("");
        kodebengkel.setText("");
        alamat.setText("");
        notelp.setText("");
        tjambuka.setText("");
        tmenitbuka.setText("");
        tjamtutup.setText("");
        tmenittutup.setText("");
    }
    
    protected void datatable() {
        Object [] baris = {"Bengkel Id", "Nama Bengkel", "Kode Bengkel", "Alamat", "Nomor Telepon Bengkel", "Jam Buka", "Jam Tutup"};
        tabmode = new DefaultTableModel(null, baris);
        tabelBengkel.setModel(tabmode);
        String sql = "select * from mst_bengkel";
        
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String a = hasil.getString("bengkelid");
                String b = hasil.getString("namabengkel");
                String c = hasil.getString("kodebengkel");
                String d = hasil.getString("alamat");
                String e = hasil.getString("notelp");
                String f = hasil.getString("jambuka");
                String g = hasil.getString("jamtutup");
                String [] data  = {a,b,c,d,e,f,g};
                tabmode.addRow(data);
                
            } 
        } catch (SQLException g){}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        namabengkel = new javax.swing.JTextField();
        kodebengkel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        notelp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bengkelid = new javax.swing.JTextField();
        bCancel = new javax.swing.JButton();
        bExit = new javax.swing.JButton();
        bEdit = new javax.swing.JButton();
        bDelete = new javax.swing.JButton();
        bSave = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelBengkel = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        cariBengkel = new javax.swing.JTextField();
        bCari = new javax.swing.JButton();
        tjambuka = new javax.swing.JTextField();
        tmenitbuka = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tjamtutup = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tmenittutup = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        namabengkel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namabengkelActionPerformed(evt);
            }
        });

        kodebengkel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodebengkelActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(51, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Form Bengkel");
        jLabel1.setToolTipText("");

        notelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notelpActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Bengkel Id");

        alamat.setColumns(20);
        alamat.setRows(5);
        jScrollPane1.setViewportView(alamat);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Nama Bengkel");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Kode Bengkel");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Alamat");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("No Telp");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Jam Buka");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Jam Tutup");

        bengkelid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bengkelidActionPerformed(evt);
            }
        });

        bCancel.setText("Cancel");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });

        bExit.setText("Exit");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });

        bEdit.setText("Edit");
        bEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditActionPerformed(evt);
            }
        });

        bDelete.setText("Delete");
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });

        bSave.setText("Save");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });

        tabelBengkel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Bengkel", "Nama Bengkel", "Kode Bengkel", "Alamat", "No Telp", "Jam Buka", "Jam Tutup"
            }
        ));
        tabelBengkel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelBengkelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelBengkel);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("Kata Kunci Pencarian");

        bCari.setText("Cari");
        bCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCariActionPerformed(evt);
            }
        });

        tjambuka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tjambukaActionPerformed(evt);
            }
        });

        jLabel10.setText(":");

        tjamtutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tjamtutupActionPerformed(evt);
            }
        });

        jLabel11.setText(":");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 424, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(343, 343, 343))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(87, 87, 87)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(notelp)
                    .addComponent(kodebengkel)
                    .addComponent(namabengkel)
                    .addComponent(bengkelid)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tjamtutup, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                            .addComponent(tjambuka))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tmenitbuka, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tmenittutup)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(36, 36, 36))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(49, 49, 49)
                        .addComponent(cariBengkel)
                        .addGap(36, 36, 36)
                        .addComponent(bCari))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bSave)
                        .addGap(18, 18, 18)
                        .addComponent(bEdit)
                        .addGap(18, 18, 18)
                        .addComponent(bDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bCancel)
                        .addGap(18, 18, 18)
                        .addComponent(bExit)))
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bengkelid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namabengkel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kodebengkel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(notelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tjambuka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tmenitbuka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tjamtutup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(tmenittutup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSave)
                    .addComponent(bEdit)
                    .addComponent(bDelete)
                    .addComponent(bCancel)
                    .addComponent(bExit))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cariBengkel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCari))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bengkelidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bengkelidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bengkelidActionPerformed

    private void namabengkelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namabengkelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namabengkelActionPerformed

    private void kodebengkelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodebengkelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodebengkelActionPerformed

    private void notelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notelpActionPerformed

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        DetailActivity detail = new DetailActivity();
        detail.setVisible(true);
        dispose();
    }//GEN-LAST:event_bExitActionPerformed

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        // TODO add your handling code here:
        kosong();
        datatable();
    }//GEN-LAST:event_bCancelActionPerformed

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        // TODO add your handling code here:
        String sql = "insert into mst_bengkel values(?,?,?,?,?,?,?)";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, bengkelid.getText());
            stat.setString(2, namabengkel.getText());
            stat.setString(3, kodebengkel.getText());
            stat.setString(4, alamat.getText());
            stat.setString(5, notelp.getText());
            stat.setString(6, tjambuka.getText().concat(":").concat(tmenitbuka.getText()));
//            stat.setString(7, tjamtutup.getText().concat(":").concat(tmenittutup.getText()));
            stat.setString(7, tjamtutup.getText()+(":")+(tmenittutup.getText()));
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            kosong();
            bengkelid.requestFocus();
            datatable();
            
        } catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data tidak Berhasil Disimpan");
        }
    }//GEN-LAST:event_bSaveActionPerformed

    private void tabelBengkelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelBengkelMouseClicked
        // TODO add your handling code here:
        
        int bar = tabelBengkel.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();
        String f = tabmode.getValueAt(bar, 5).toString();
        String g = tabmode.getValueAt(bar, 6).toString();
        String jamBuka, menitBuka, jamTutup, menitTutup;
        String[] split = f.split(":");
        jamBuka = split[0];
        menitBuka = split[1];
        String[] split2 = g.split(":");
        jamTutup = split2[0];
        menitTutup = split2[1];
        
        bengkelid.setText(a);
        namabengkel.setText(b);
        kodebengkel.setText(c);
        alamat.setText(d);
        notelp.setText(e);
        tjambuka.setText(jamBuka);
        tmenitbuka.setText(menitBuka);
        tjamtutup.setText(jamTutup);
        tmenittutup.setText(menitTutup);
    }//GEN-LAST:event_tabelBengkelMouseClicked

    private void bEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditActionPerformed
        // TODO add your handling code here:
        String sql = "update mst_bengkel set namabengkel=?, kodebengkel=?, alamat=?, notelp=?, jambuka=?, jamtutup=? where bengkelid=?";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, namabengkel.getText());
            stat.setString(2, kodebengkel.getText());
            stat.setString(3, alamat.getText());
            stat.setString(4, notelp.getText());
            stat.setString(5, tjambuka.getText().concat(":").concat(tmenitbuka.getText()));
            stat.setString(6, tjamtutup.getText().concat(":").concat(tmenittutup.getText()));
            stat.setString(7, bengkelid.getText());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            kosong();
            bengkelid.requestFocus();
            datatable();
            
        } catch (SQLException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Data tidak Berhasil Disimpan");
        }
    }//GEN-LAST:event_bEditActionPerformed

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed

        // TODO add your handling code here:
        String sql = "delete from mst_bengkel where bengkelid=?";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, bengkelid.getText());

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
            kosong();
            bengkelid.requestFocus();
            datatable();
            
        } catch (SQLException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Data tidak Berhasil Dihapus");
        }
    }//GEN-LAST:event_bDeleteActionPerformed

    private void tjambukaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tjambukaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tjambukaActionPerformed

    private void tjamtutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tjamtutupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tjamtutupActionPerformed

    private void bCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCariActionPerformed
        // TODO add your handling code here:
        Object [] baris = {"Bengkel Id", "Nama Bengkel", "Kode Bengkel", "Alamat", "Nomor Telepon Bengkel", "Jam Buka", "Jam Tutup"};
        tabmode = new DefaultTableModel(null, baris);
        tabelBengkel.setModel(tabmode);
        String sql = "select * from mst_bengkel where bengkelid like '%"+cariBengkel.getText()+"%' OR namabengkel like '%"+cariBengkel.getText()+"%' "
                + "OR kodebengkel like '%"+cariBengkel.getText()+"%' OR alamat like '%"+cariBengkel.getText()+"%' OR notelp like '%"+cariBengkel.getText()+"%' "
                + "OR jambuka like '%"+cariBengkel.getText()+"%' OR jamtutup like '%"+cariBengkel.getText()+"%' ";
        
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String a = hasil.getString("bengkelid");
                String b = hasil.getString("namabengkel");
                String c = hasil.getString("kodebengkel");
                String d = hasil.getString("alamat");
                String e = hasil.getString("notelp");
                String f = hasil.getString("jambuka");
                String g = hasil.getString("jamtutup");
                String [] data  = {a,b,c,d,e,f,g};
                tabmode.addRow(data);
                
            } 
        } catch (SQLException e){}
    }//GEN-LAST:event_bCariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(infocbJamBuka)) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tampilan.FormBengkel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tampilan.FormBengkel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tampilan.FormBengkel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tampilan.FormBengkel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tampilan.FormBengkel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat;
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bCari;
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bEdit;
    private javax.swing.JButton bExit;
    private javax.swing.JButton bSave;
    private javax.swing.JTextField bengkelid;
    private javax.swing.JTextField cariBengkel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kodebengkel;
    private javax.swing.JTextField namabengkel;
    private javax.swing.JTextField notelp;
    private javax.swing.JTable tabelBengkel;
    private javax.swing.JTextField tjambuka;
    private javax.swing.JTextField tjamtutup;
    private javax.swing.JTextField tmenitbuka;
    private javax.swing.JTextField tmenittutup;
    // End of variables declaration//GEN-END:variables
}
